### ISSUE TITLE
[Design] NisAI Stencil Components

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#10]
Dishita: 
- [ ] PWA flow v1 - 13th / 14th May 2024
    - [ ] Onboarding screen
    - [ ] Select grade 
    - [ ] Select competency
    - [ ] Assessment screen (FLN)
    - [ ] Result Screen

Om: 
- [ ] ORF - 20th / 21st May 2024
    - [ ] Reading screen + Mascot + Submit + In Line result
    - [ ] Result screen (same as above)

Pending
- [ ] Admin panel

**Comment by rohitsamagra** [comment]
Figma link here:
