### ISSUE TITLE
Admin Panel - Assessment Management - Product Scoping

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#14]
### NisAI : Admin Panel
PRD: https://docs.google.com/document/d/104pNxv_RbouK0fJzXNmbVNyWs1etYTch-maXckySTlM/edit
Very Rough sketch in Figma: https://www.figma.com/file/KEv3Bga4hygJiw4QPFMxx3/NL-App_May_2023?mode=dev

- [x] Scoping of features
- [x] PRD

OOS:
- ~[ ]  Setup of admin panel~
- ~[ ]  Auth implementation for Admin and Orgs~
- ~[ ]  Creation of Orgs~
- ~[ ]  Dataset builder integration~
- ~[ ]  Config creation flows~
- ~[ ]  Export config to Orgs~

**Comment by tushar5526** [comment]
Agreed Generation flow cc @rohitsamagra @karntrehan 

1. Select Competency
2. Select Prompt Schema Format (3 default formats to chose from - Comprehension, QA, BSTT)
3. Select Question Type (Single select, multi-select, free-text)
4. Edit prompt for questionnaires generated automatically 
5. Iterate for ’n’ number of examples specified. 
6. Specify reasons for the generated questionnaires.
7. Save the prompt
8. Convert to GAP or see the final output. 
9. Ingest as Questionnaires.

**Comment by rohitsamagra** [comment]
- Competency to player mapping, how does it need to happen? @rohitsamagra @karntrehan to discuss with @tushar5526

**Comment by karntrehan** [comment]
1st iteration of the design seen. Next meeting scheduled for 2nd July.

**Comment by VargishChauhan** [comment]
For  V1, Question generation will not be there. Admin can upload , review, save and ingest the questions.
@karntrehan @amit-s19

**Comment by charanpreet-s** [comment]
- @VargishChauhan to update PRD and scoping
- Waiting for Dt to come back with updated designs

**Comment by karntrehan** [comment]
Dropped.
