### ISSUE TITLE
[Documentation] Audit and updation

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#17]
We need to audit our current documentation and make sure it is aligned with our current version. 

https://bharatsahaiyak-docs.vercel.app/nipun_sahaiyak/intro

## Introduction 
All okay 

## Assessments 

- [ ] Update architecture doc
- [ ] Add diagram for steps and where each step is run. Flow diagram?
- [ ] Consider taking out visualization?

## Generation

- [ ] Talk about autotune and link to autotune
- [ ] Give examples in descriptions of json. Currently not intuitive
- [ ] Add diagram of how generation falls in the entire scheme of things
- [ ] Mention that this is a skippable step if states already have content generated
- [ ] Mention that states can use the base pack provided by us

## Ingestion

- [ ] Give examples in descriptions of json. Currently not intuitive
- [ ] Add diagram of how ingestion falls in the entire scheme of things
- [ ] Define (via diagram) how competency, players and questionaires play together.

## Transformation
- [ ] Give examples in descriptions of json. Currently not intuitive
- [ ] Add diagram of how transformation falls in the entire scheme of things
- [ ] Add BSTT transformer
- [ ] Add GRA transformer

## Execution

- [ ] Add detailed docs about web and android orchestrator
- [ ] Add diagram of how orchestrator falls in the entire scheme of things

## Visualization
- [ ] Take it out? Confirm with Product

## Admin

- [ ] Take it out

## BFF

- [ ] Add more details here 

## Data service

- [ ] Explain BE architecture in detail
- [ ] Add details for each table 
- [ ] Add these tables are for assessments

## Core service
- [ ] Explain BE architecture in detail
- [ ] Add details for each table 

## Web Orchestrator

- [ ] Define the architecture in detail
- [ ] Add diagrams for players
- [ ] Add installation in more prominence

## Releases
No change as of now

## Web Orchestrator - Installation

- [ ] Consider moving to the web orchestrator page itself

## Suggested Structure
Nipun SahAIyak
- Introduction
- Features
    - User management
    - Assessment Cycle Management
    - Assessment management
        - Steps
            - Generation
            - Ingestion
            - Transformation
            - Execution
            - Visualization
- BE Components
    - Core Service
    - Data Service
    - BFF
    - User authentication
    - etc..
- FE components
    - Web Orchestrator 
    - Android Orchestrator
    - Admin
- Releases 
- Sandbox

**Comment by dhruv-1001** [comment]
@karntrehan to share list by EOD.

**Comment by karntrehan** [comment]
@amit-s19 @charanpreet-s @dhruv-1001 kindly review.

**Comment by dhruv-1001** [comment]
## Assessment
- Add diagram for steps and where each step is run. Flow diagram? -> I think this will be covered inside of each step in detail. Do we need this here?
- Consider taking out visualization? -> Is this the result's page? If so, let's keep this, we just need to upload the screenshots of pages that we have build. Also, it feels off taking out one of the 5 main steps we have divided the architecture into.

## Generation
- Mention that states can use the base pack provided by us -> We don't have it finalised where we would keep this data. Let's come up with that first, then add this detail?

## Transformation 
- Can also add the new added interface, and how to contribute if anyone want to add transformation for new player type.

## BFF
- No development on this yet. Let's wait till we have this more defined?

## data-service
- Add these tables are for assessments -> Not clear.

## Suggested Structure
Inside of `BE Components` should we also add other services `ingestor` & `generation-ms`, and also the players that we have created `bstt-player`.

**Comment by karntrehan** [comment]
Implementation ticket: #24
