### ISSUE TITLE
[Testing] Fixing issues reported by PT

### ISSUE THREAD

**Issue by Burhan1110** [NipunSahAIyak/.github#21]
Issues reported: https://docs.google.com/spreadsheets/d/1wIoFFfaSb4Fvs0WJG3dUTiaVtQuZhwc_xiwnspsZSJ4/edit?gid=1061436948#gid=1061436948

**Comment by karntrehan** [comment]
Release getting tracked here: https://github.com/NipunSahAIyak/web-orchestrator/issues/27
