### ISSUE TITLE
[Product Scoping]User Agreement screen for audio collection

### ISSUE THREAD

**Issue by Burhan1110** [NipunSahAIyak/.github#22]
A screen asking for user consent to collect audio samples at the time of logging in the first time.

**Comment by Burhan1110** [comment]
Design team is working on this screen.

**Comment by Burhan1110** [comment]
![Image](https://github.com/user-attachments/assets/00170e69-d30a-4ac7-8e41-e59f3005737e)

**Comment by AakashSatpute119** [comment]
Update figma link  on ticket and close.

**Comment by Burhan1110** [comment]
https://www.figma.com/design/viU7EdVpIDwmq38uWMgxC2/Nipun-Bharat-AI?node-id=100-1539&t=LWU85bepVfptYxrM-0
