### ISSUE TITLE
Nisai Test Cases

### ISSUE THREAD

**Issue by amit-s19** [NipunSahAIyak/.github#23]
# Test Cases across applications

### Web tasks
- [x] Setup Jest and(optional) react-testing-library for unit tests
- [x] Setup CI on github actions
- [x] Unit tests for components
#### List of components for unit tests:
- [x] Header
- [x] Primary Button
- [x] Secondary Button
- [x] Info Card
- [x] Profile Card
- [x] Result Card
- [x] Teacher Card
- [x] AuthLayout
- [x] Layout with back button
- [x] Login Form
- [x] Network Status Indicator
- [x] Process Flow Chart
- [x] Protected Layout
- [x] Intro Card
- [x] Summary Section
- [x] Study Section

### Total Tests Written - 101/100

**Comment by karntrehan** [comment]
To be picked from tomorrow.

**Comment by karntrehan** [comment]
@amit-s19 working on this as @tgBuntikki is not available right now.

**Comment by VargishChauhan** [comment]
Need to add more test cases

**Comment by amit-s19** [comment]
![Image](https://github.com/user-attachments/assets/36c1dce9-5a82-474c-9b21-3828ddc3c4df)

**Comment by amit-s19** [comment]
Added a total of 101 Test cases throughout the application. Here is the coverage report :


![Image](https://github.com/user-attachments/assets/a9ff1ccd-0a0a-4477-abc6-76ca4089bf11)


### PR - https://github.com/NipunSahAIyak/web-orchestrator/pull/55

**Comment by AakashSatpute119** [comment]
- Merge this PR and close
