### ISSUE TITLE
NisAI Release 0.3.0

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#26]
## Current releases: 

- .github - 0.0.3 - https://github.com/NipunSahAIyak/.github/releases/tag/untagged-6cc668527835bd231dbd
- ingestor - 0.2.1 - https://github.com/NipunSahAIyak/ingestor/releases/tag/v0.2.1
- data-service - 0.2.1 - https://github.com/NipunSahAIyak/data-service/releases/tag/v0.2.1
- core-service - [v0.2.1](https://github.com/NipunSahAIyak/core-service/releases/tag/v0.2.1)
- Web executor - [v0.2.1](https://github.com/NipunSahAIyak/web-orchestrator/releases/tag/v0.2.1)
- Android executor - [v0.2.0](https://github.com/NipunSahAIyak/android-nisai-orchestrator/releases/tag/v0.2.0)
- Devops - [v0.0.2](https://github.com/NipunSahAIyak/devops/releases/tag/v0.0.2)
- https://github.com/NipunSahAIyak/android-gra-assessment-player - ?
- https://github.com/NipunSahAIyak/generation-ms - ?
- https://github.com/NipunSahAIyak/workflow - ?
- https://github.com/NipunSahAIyak/web-bstt-player - ?
- https://github.com/NipunSahAIyak/assessment-agent - ?
- https://github.com/NipunSahAIyak/android-odk-assessment-player - ?
- https://github.com/NipunSahAIyak/android-bstt-assessment-player - ?

### Web
* Architecture revamp - BSTT player, ODK Player, Creation of Protocol, Web Orchestrator creation, Reference app
* Test cases - 95% coverage of all modules
* CI Integration on Github
* Telemetry enhancements in BSTT Player
* Bug fixes

INP:
* Stencil migration
* Offline BSTT player

### Android 
* Telemetry enhancements in android-orchestrator, protocol and bstt.
* BSTT player enhancements
* Bug fixes
 
Stencil Repo:
* Stencil mobile

### BE
* User and cycle management CRUD development
* assessment-agent
    * [About](https://docs.google.com/document/d/11sPKSWxc0y6DvdFyGrUDP7eIGbbigSGNa4Te1QjNBLA/edit)
* Test cases - 80% code coverage (DS + CS)
* Telemetry enhancements in Nipun ASR Service (TBN - @dhruv-1001)
* Upgraded devops to support minio
* Bug fixes in DS

INP:
* User and cycle management Client API development
* Database audit logs
* Server Migration scripts for User and cycle management

### Data science
* BSTT API enhancements (v4) - Time warping for scope, Postprocessors - purnviram, `-` & encoding fixes, bhashini initial API call enhancements (when required - time bound & when new model shared), telemetry, logs, configurable model name, etc..

## Product Release Notes 
- BSTT enhancements only

## Collaterals

**Comment by dhruv-1001** [comment]
- Will be freezing development on master branch for all repositories at the end of first Half on Friday (20th September)
- To send out v0.3.0 release email at 5PM.

**Comment by VargishChauhan** [comment]
Will pickup it on 19th Sept'24

**Comment by karntrehan** [comment]
## Decision on BSTT: 
* Structure to remain the same. Nipun ASR > BSTT API > Bhashini and back. 
* BSTT Service to have 2 APIs: 
    1. `/api/asr` - Gives asr for an input language
    2. `api/asr/verify` - Creates ASR for an input language and checks if audio matches a pre-defined text.

Suggested structures below:

### `/api/asr`

Request: 
```json
{
  "input_language": "hi",
  "model": "{optional}",
  "audio_file": "audio.wav"
}
```

Response: 
```json
{
  "language": "hi",
  "model": "{optional}",
  "transcription": "Hello world. My name is slim shady.",
  "telemetry": {}
}
```

### `/api/asr/verify`

Request: 
```json
{
  "language": "hi",
  "model": "{optional}",
  "text_read": "",
  "match_status": {},
  "fuzz_match": "",
  "distance_cutoff": "",
  "audio_file": "audio.wav"
}
```

Response: 
```json
{
  "language": "hi",
  "model": "{optional}",
  "match_status": {},
  "telemetry": {}
}
```

**Comment by sukh-ai** [comment]
@karntrehan We can have versions as well as part of BSTT Service 2 API's 
For example
1. /api/asr. --> /api/asr/v1 or /api/asr/v2
2. /api/asr/verify  --> /api/asr/verify/v2 or /api/asr/verify/v4
cc: @dhruv-1001 @GautamR-Samagra

**Comment by dhruv-1001** [comment]
Release tracker.
Web @amit-s19 
- [x] web-bstt-player
- [x] workflow
- [x] web-assessment-player-protocol
- [x] odk-player
- [x] web-orchestrator-module

BE @dhruv-1001 
- [x] data-service
- [x] core-service
- [x] nisai-asr-service
- [x] generation-ms
- [x] devops-v2
- [x] assessment-agent
- [x] ingestor

Android @charanpreet-s 
- [x] android-nisai-orchestrator
- [x] android-odk-assessment-player
- [x] android-gra-assessment-player
- [x] android-bstt-assessment-player
- [x] android-assessment-player-protocol

**Comment by karntrehan** [comment]
Release sent out. Documentation update to follow: #24.
